# Generated by Django 4.2.13 on 2024-06-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instrument',
            fields=[
                ('instrument_id', models.AutoField(primary_key=True, serialize=False)),
                ('instrument_name', models.CharField(max_length=20)),
                ('instrument_prize', models.IntegerField()),
                ('instrument_quantity', models.IntegerField()),
                ('instrument_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_name', models.CharField(max_length=20)),
                ('sales_prize', models.IntegerField()),
                ('sales_quantity', models.IntegerField()),
                ('sales_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=20)),
                ('stock_prize', models.IntegerField()),
                ('stock_quantity', models.IntegerField()),
                ('stock_date', models.DateField()),
                ('stock_expiry', models.DateField()),
            ],
        ),
    ]
